In [1]:
# 0. 사용할 패키지 불러오기
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.preprocessing.image import ImageDataGenerator


Using TensorFlow backend.
/Users/mega/miniconda3/envs/mlkeras/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)


In [2]:
# 랜덤시드 고정시키기
np.random.seed(3)

In [3]:
# 1. 데이터 생성하기
train_datagen = ImageDataGenerator(rescale=1./255)

In [4]:
train_generator = train_datagen.flow_from_directory(
        'handwriting_shape/train',
        target_size=(24, 24),
        batch_size=3,
        class_mode='categorical')

Found 45 images belonging to 3 classes.


In [5]:
test_datagen = ImageDataGenerator(rescale=1./255)

In [6]:
test_generator = test_datagen.flow_from_directory(
        'handwriting_shape/test',
        target_size=(24, 24),    
        batch_size=3,
        class_mode='categorical')

Found 15 images belonging to 3 classes.


In [7]:
# 2. 모델 구성하기
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=(24,24,3)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(3, activation='softmax'))

In [8]:
# 3. 모델 학습과정 설정하기
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [9]:
# 4. 모델 학습시키기
model.fit_generator(
        train_generator,
        steps_per_epoch=15,
        epochs=50,
        validation_data=test_generator,
        validation_steps=5)

Epoch 1/50
15/15 [==============================] - 1s 42ms/step - loss: 1.0185 - acc: 0.4889 - val_loss: 0.5618 - val_acc: 0.6667
Epoch 2/50
15/15 [==============================] - 0s 14ms/step - loss: 0.3544 - acc: 0.7778 - val_loss: 0.3458 - val_acc: 0.8000
Epoch 3/50
15/15 [==============================] - 0s 18ms/step - loss: 0.1321 - acc: 0.9778 - val_loss: 0.0936 - val_acc: 1.0000
Epoch 4/50
15/15 [==============================] - 0s 20ms/step - loss: 0.0189 - acc: 1.0000 - val_loss: 0.1666 - val_acc: 0.8667
Epoch 5/50
15/15 [==============================] - 0s 16ms/step - loss: 0.0023 - acc: 1.0000 - val_loss: 0.0843 - val_acc: 1.0000
Epoch 6/50
15/15 [==============================] - 0s 20ms/step - loss: 8.2885e-04 - acc: 1.0000 - val_loss: 0.0725 - val_acc: 1.0000
Epoch 7/50
15/15 [==============================] - 0s 19ms/step - loss: 5.4146e-04 - acc: 1.0000 - val_loss: 0.0823 - val_acc: 1.0000
Epoch 8/50
15/15 [==============================] - 0s 18ms/step - loss: 4.

In [10]:
# 6. 모델 평가하기
print("-- Evaluate --")
scores = model.evaluate_generator(test_generator, steps=5)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

-- Evaluate --
acc: 100.00%


In [13]:
# 7. 모델 사용하기
print("-- Predict --")
output = model.predict_generator(test_generator, steps=5)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

-- Predict --


In [14]:
print(test_generator.filenames)

['circle/circle016.png', 'circle/circle017.png', 'circle/circle018.png', 'circle/circle019.png', 'circle/circle020.png', 'rectangle/rectangle016.png', 'rectangle/rectangle017.png', 'rectangle/rectangle018.png', 'rectangle/rectangle019.png', 'rectangle/rectangle020.png', 'triangle/triangle016.png', 'triangle/triangle017.png', 'triangle/triangle018.png', 'triangle/triangle019.png', 'triangle/triangle020.png']


In [15]:
print(test_generator.class_indices)

{'triangle': 2, 'circle': 0, 'rectangle': 1}


In [16]:
print(output) 

[[0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.859 0.001 0.140]
 [0.000 1.000 0.000]
 [1.000 0.000 0.000]
 [1.000 0.000 0.000]
 [0.000 1.000 0.000]
 [0.027 0.742 0.231]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.000 1.000 0.000]
 [0.000 0.000 1.000]
 [0.000 1.000 0.000]
 [1.000 0.000 0.000]
 [1.000 0.000 0.000]]
